version: "3.7"
services:
  react-prod:
    container_name: e-commerce-prod
    build:
      context: .
      dockerfile:
        Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:80"
